### ISSUE TITLE
重构 TaskLeftListView.vue 的实现，基于功能拆分子组件

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/vue3-dida#14]
目前 TaskLeftListView.vue 可以继续拆分逻辑了

一个是和清单相关 UI 逻辑
<img width="262" alt="image" src="https://user-images.githubusercontent.com/12064746/210196559-0a4be4a2-dcd0-4736-853b-3b540a7fe413.png">

一个是和特殊project 的相关 UI 逻辑
<img width="346" alt="image" src="https://user-images.githubusercontent.com/12064746/210196566-5b702756-c3a4-46fa-bf92-76411dad8c21.png">

可以重构成：
TaskLeftListView
    - 清单相关 UI 逻辑.vue
    - 特殊project 的相关 UI 逻辑.vue

要注意的问题是 active 的 project 只能有一个
<img width="307" alt="image" src="https://user-images.githubusercontent.com/12064746/210196602-5047ead2-19de-43f0-99ce-5a519cbc8c3d.png">

所以要考虑到 active 的问题

**Comment by YFAnt** [comment]
领走

**Comment by cuixiaorui** [comment]
done #30
