### ISSUE TITLE
左侧栏和右侧的编辑区域可以拖拽

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/vue3-dida#15]
![dida-task-1](https://user-images.githubusercontent.com/12064746/210196775-61647da0-cfef-4c89-8bf9-d358bf98ac2c.gif)

## Tasking
- [ ] 鼠标到边框的时候显示拖拽的 icon
- [ ] 鼠标在边框的时候可以拖拽控制区域的宽度
- [ ] 区域的宽度有最小值和最大值的概念

**Comment by xianjianlf2** [comment]
领任务

**Comment by cuixiaorui** [comment]
done #20
