### ISSUE TITLE
优化 input 的样式

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/vue3-dida#31]
<img width="655" alt="image" src="https://user-images.githubusercontent.com/12064746/210071048-1ca52c08-c635-4075-bd9b-168cabedcfa8.png">

<img width="628" alt="image" src="https://user-images.githubusercontent.com/12064746/210071059-89496b45-78b9-4469-8d5f-1cad20f2e398.png">

taskItem 两个显示状态  
一个是 active 的时候，高亮 task （input 就不可以高亮了）
另外一个是 hover 的样式

**Comment by jobn123** [comment]
领任务

**Comment by cuixiaorui** [comment]
done #35
