### ISSUE TITLE
可以显示/隐藏侧边栏

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/vue3-dida#36]
![dida-task1](https://user-images.githubusercontent.com/12064746/211269327-53089e9d-a3a6-4ca2-891e-6fe091112662.gif)

点击按钮的时候 左侧的侧边栏隐藏 
再次点击后 显示左侧的侧边栏

**Comment by jobn123** [comment]
领走

**Comment by cuixiaorui** [comment]
done
