### ISSUE TITLE
改善输入框的样式

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/vue3-dida#6]
现在的输入框的样式
<img width="836" alt="image" src="https://user-images.githubusercontent.com/12064746/210049631-70191501-ada0-4df5-a53b-b723ec9bd984.png">

期望的样式
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/12064746/210049690-768c3309-ecde-46af-80b3-f20d1a13e919.png">

**Comment by RamirezET** [comment]
#22

**Comment by cuixiaorui** [comment]
done #21
