### ISSUE TITLE
改善左边栏的样式

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/vue3-dida#7]
现在的样式
<img width="399" alt="image" src="https://user-images.githubusercontent.com/12064746/210049901-d08ed781-c96a-4c3d-8165-4796582794a8.png">

期望的样式
<img width="231" alt="image" src="https://user-images.githubusercontent.com/12064746/210049865-6626ff05-bdb8-492c-85f7-0e5d5e24540f.png">

**Comment by Stream-web** [comment]
这个我来吧

**Comment by cuixiaorui** [comment]
已经完成
