### ISSUE TITLE
设置面板功能

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/vue3-dida#8]
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/12064746/211271918-ae4fcb6c-2809-4ddb-a4cd-f7d90c8ccef5.png">

## Tasking
- [ ] url为 #settings 的时候跳转到设置面板
- [ ] 显示左侧的导航栏
        - 智能清单
        - 主题
- [ ] 点击完成按钮后回到主页面
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/12064746/211272205-8640afde-d416-46ab-a26b-6c201f2e4416.png">

## 主题

<img width="959" alt="image" src="https://user-images.githubusercontent.com/12064746/211273009-64e1750f-dc34-4f2d-8d03-4f8b9039e8b9.png">

只支持黑白就可以了

**Comment by alexzhang1030** [comment]
这个我来吧

**Comment by Hazel-Lin** [comment]
> 

啥都给你整完啦hhh
