### ISSUE TITLE
点击空白处聚焦最后一个 task 的问题

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/vue3-dida#9]
问题复现如下：
![vue3-todo](https://user-images.githubusercontent.com/12064746/210050797-2dc0fc44-7d5a-4fe4-b272-9bcfcfa422a5.gif)

**Comment by cuiyiming1998** [comment]
这里貌似是contenteditable的问题
MDN的contentededitable也有这个bug
![image](https://user-images.githubusercontent.com/25956970/210052027-4f4c8891-20c4-48a9-80c3-6d6d3772d970.png)
正在尝试不用contenteditable的方法

**Comment by alexzhang1030** [comment]
想到了一种好玩的方式 🤣 在 todoItem 下面插入一个 w-full 但是 height 为 0 的 div，设置 `contenteditable` 为 false，应该就能解决这个奇怪的 bug 了

**Comment by cuiyiming1998** [comment]
> 想到了一种好玩的方式 🤣 在 todoItem 下面插入一个 w-full 但是 height 为 0 的 div，设置 `contenteditable` 为 false，应该就能解决这个奇怪的 bug 了

这个方法我试过了 高度不能为0 好像必须得有一点高度

**Comment by alexzhang1030** [comment]
对，我加了 1px 就行了

**Comment by k983551019** [comment]
秀啊
